Version 0.11
SpineEventEngine/client-cpp pull request #21
Opened 2018-10-08 16:40 UTC by vladimir-moiseiev

This PR updates dependency of spine-client version to 0.11.00.
Also, updating own version to 0.11

2018-10-08 17:49 UTC, armiol requested changes
@vladimir-moiseiev please see my comments and let's discuss in person.

2018-10-08 17:49 UTC, armiol commented on VERSION
> +0.11.0
Technically, in Spine server we don't have `0.11.00`, we have `0.11.00-SNAPSHOT`.

Therefore, here you should also have `0.11.00-SNAPSHOT`.

2018-10-08 17:49 UTC, armiol commented on test/actor_request_factory_test.cc
> -    ZoneId* zone_id = ZoneId::default_instance().New();
Let's discuss why the code related to zone ID is now gone. I am not sure, since the `ActorContext` message still has those.

2018-10-12 12:35 UTC, vladimir-moiseiev commented
@armiol PTAL

2018-10-12 12:49 UTC, armiol approved these changes
@vladimir-moiseiev LGTM.

2018-10-12 12:56 UTC, merged